runtime: python310
entrypoint: gunicorn -t 300 -b :8080 -w 3 -k uvicorn.workers.UvicornWorker main:app
instance_class: F1

env_variables:
  RUMOR_URL: "%RUMOR_URL_PLACEHOLDER%"
  RUMOR_TOKEN: "%RUMOR_TOKEN_PLACEHOLDER%"
  MONGODB_URL: "%MONGODB_URL_PLACEHOLDER%"
  MONGODB_USER: "%MONGODB_USER_PLACEHOLDER%"
  MONGODB_PASSWORD: "%MONGODB_PASSWORD_PLACEHOLDER%"
  OPENAI_ORG: "%OPENAI_ORG_PLACEHOLDER%"
  OPENAI_API_KEY: "%OPENAI_API_KEY_PLACEHOLDER%"
  BEARER_TOKEN: "%BEARER_TOKEN_PLACEHOLDER%"